CellphoneS/Areas/Admin/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CellphoneS.Models.EF;
using CellphoneS.Models.DAO;
namespace CellphoneS.Areas.Admin.Controllers
{
    public class PaymentController : BaseController
    {
        // GET: Admin/Payment
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Unpaid()
        {
            var dao = new OrderDAO().GetOrder();
            return View(dao);
        }
        [HttpPost]
        public JsonResult accept(int id)
        {
            var result = new OrderDAO().accept(id);
            return Json(new
            {
                DaThanhToan = result
            });
        }
        public ActionResult Paid()
        {
            var dao = new OrderDAO().Paid();
            return View(dao);
        }
        [HttpPost]
        public JsonResult delivery(int id)
        {
            var result = new OrderDAO().delivery(id);
            return Json(new
            {
                TinhTrangGiaoHang = result
            });
        }
        public ActionResult success()
        {
            var result = new OrderDAO().Delivery();
            return View(result);
        }
    }
}

CellphoneS/Areas/Admin/Views/Payment/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<div class="container mt-2">
    <h3 class="mb-3">Quản Lý Đơn Hàng</h3>
    <ul class="nav nav-tabs text-center justify-content-center">
        <li class="nav-item">
            <a class="nav-link active" data-bs-toggle="tab" href="#home">
                Chưa Thanh Toán
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" href="#profile">
                Đang Vận Chuyển
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" href="#contact">
                Giao Hàng Thành Công
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="home">
            <div class="row border g-0 rounded shadow-sm">
                <table>
                    @{Html.RenderAction("Unpaid", "Payment");}
                </table>
            </div>
        </div>
        <div class="tab-pane" id="profile">
            <div class="row border g-0 rounded shadow-sm">
                @{Html.RenderAction("Paid", "Payment");}
            </div>
        </div>
        <div class="tab-pane" id="contact">
            <div class="row border g-0 rounded shadow-sm">
                @{Html.RenderAction("success", "Payment");}
            </div>
        </div>
    </div>

</div>

<style>
    .dimension {
        width: 500px;
        height: 300px;
    }

    .nav-tabs .nav-link.active {
        background-color: #9400d3;
        color: #fff;
        border: 3px solid #9400d3;
    }

    .nav-tabs .nav-link {
        background-color: #fff;
        color: #9400d3;
        border: 3px solid #9400d3;
        margin-right: 2rem;
        padding-left: 3rem;
        padding-right: 3rem;
    }

        .nav-tabs .nav-link:hover {
            border: 3px solid #9400d3;
        }

    .nav-tabs {
        border-bottom: 1px solid #9400d3;
    }

    .tab-content {
        border: 1px solid #9400d3;
        padding: 20px;
    }
</style>

CellphoneS/Areas/Admin/Views/Payment/Paid.cshtml
@model IEnumerable<CellphoneS.Models.EF.DonDatHang>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KhachHang.TenKH) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayDat) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TinhTrangGiaoHang) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayGiao) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DaThanhToan) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UuDai) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HuyDon) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai) 
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KhachHang.TenKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayDat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TinhTrangGiaoHang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayGiao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DaThanhToan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UuDai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HuyDon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TrangThai)
                </td>
                <td>
                    <a href="#" class="btn btn-primary" data-id="@item.MaDDH" id="btnsuccess">
                        Giao Hàng Thành Công
                    </a>
                </td>
            </tr>
        }
    </tbody>

</table>
<script>
    $(document).ready(function () {
        var delivery = {
            init: function () {
                delivery.registerEvents();
            },
            registerEvents: function () {
                $("#btnsuccess").off('click').on('click', function (e) {
                    e.preventDefault();
                    var btn = $(this)
                    var id = btn.data('id')
                    $.ajax({
                        url: "/Admin/Payment/delivery",
                        data: { id: id },
                        dataType: "json",
                        type: "POST",
                        success: function (response) {

                            if (response.TinhTrangGiaoHang == true) {

                                location.reload();
                            }
                        }
                    })
                })
            }
        }
        delivery.init();
    }
</script>

CellphoneS/Areas/Admin/Views/Payment/Unpaid.cshtml
@model IEnumerable<CellphoneS.Models.EF.DonDatHang>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KhachHang.TenKH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayDat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TinhTrangGiaoHang)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayGiao) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DaThanhToan) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UuDai) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HuyDon) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai) 
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KhachHang.TenKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayDat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayGiao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DaThanhToan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UuDai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HuyDon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TrangThai)
                </td>
                <td>
                    <a href="#" class="btn btn-primary" data-id="@item.MaDDH" id="btnAccept">
                        Duyệt Đơn Hàng
                    </a>

                </td>
            </tr>

        }
    </tbody>

</table>
<script>

    $(document).ready(function () {
        var order = {
            init: function () {
                order.registerEvents();
            },
            registerEvents: function () {
                $("#btnAccept").off('click').on('click', function (e) {
                    e.preventDefault();
                    var btn = $(this)
                    var id = btn.data('id')
                    $.ajax({
                        url: "/Admin/Payment/accept",
                        data: { id: id },
                        dataType:"json",
                        type: "POST",
                        success: function (response) {
                            console.log("1")
                            if (response.TinhTrangGiaoHang == true) {

                                location.reload();
                            }
                        }
                    })
                })
            }
        }
        order.init();
    }
</script>

CellphoneS/Areas/Admin/Views/Payment/success.cshtml
@model IEnumerable<CellphoneS.Models.EF.DonDatHang>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KhachHang.TenKH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayDat) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TinhTrangGiaoHang) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayGiao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DaThanhToan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UuDai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HuyDon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai) 
            </th>

        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KhachHang.TenKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayDat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TinhTrangGiaoHang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayGiao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DaThanhToan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UuDai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HuyDon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TrangThai)
                </td>

            </tr>
        }
    </tbody>
</table>